<a href="https://colab.research.google.com/github/RJ-0605/Deep-Learning-Jovian-Zero-GANS/blob/main/how_to_use_pytorch_tensors_for_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1TnTxvREAL3A7sJxgdsQlf8Ib6nVBGXdy')

> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Title Here

An short introduction about PyTorch and about the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1: torch.linspace

torch.linspace is used to create a 1D equally spaced tensor between the values start and end . 

We can specify the size of the tensor with the steps parameters.

 The default is steps=100

In [ ]:
# Example 1 - working

torch.linspace(1, 10)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Not providing a value for linspace's steps is deprecated and will throw a runtime error in a future release. This warning will appear only once per process. (Triggered internally at  /pytorch/aten/src/ATen/native/RangeFactories.cpp:23.)
  


tensor([ 1.0000,  1.0909,  1.1818,  1.2727,  1.3636,  1.4545,  1.5455,  1.6364,
         1.7273,  1.8182,  1.9091,  2.0000,  2.0909,  2.1818,  2.2727,  2.3636,
         2.4545,  2.5455,  2.6364,  2.7273,  2.8182,  2.9091,  3.0000,  3.0909,
         3.1818,  3.2727,  3.3636,  3.4545,  3.5455,  3.6364,  3.7273,  3.8182,
         3.9091,  4.0000,  4.0909,  4.1818,  4.2727,  4.3636,  4.4545,  4.5455,
         4.6364,  4.7273,  4.8182,  4.9091,  5.0000,  5.0909,  5.1818,  5.2727,
         5.3636,  5.4545,  5.5455,  5.6364,  5.7273,  5.8182,  5.9091,  6.0000,
         6.0909,  6.1818,  6.2727,  6.3636,  6.4545,  6.5455,  6.6364,  6.7273,
         6.8182,  6.9091,  7.0000,  7.0909,  7.1818,  7.2727,  7.3636,  7.4545,
         7.5455,  7.6364,  7.7273,  7.8182,  7.9091,  8.0000,  8.0909,  8.1818,
         8.2727,  8.3636,  8.4545,  8.5455,  8.6364,  8.7273,  8.8182,  8.9091,
         9.0000,  9.0909,  9.1818,  9.2727,  9.3636,  9.4545,  9.5455,  9.6364,
         9.7273,  9.8182,  9.9091, 10.00

Explanation about example

In [ ]:
# Example 2 - working
# Here we specify the number of steps 

torch.linspace(start=1, end=10, steps=5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
# We have to specify the end or the function breaks 

torch.linspace(start=1,  steps=5)


TypeError: ignored

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra


'https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra'

## Function 2: torch.eye

torch.eye returns a 2D tensor with the values of diagonals as 1 and other values as 0

The function expects two parameters — n and m .

 If m is not specified, then it returns a 2D tensor of size nxn

In [ ]:
# Example 1 - working
# here the function returns a 2-D tensor or nxm


torch.eye(n=4, m=5)


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

Explanation about example

In [ ]:
# Example 2 - working
# here the function returns a 2-D tensor or nxn since m is not specified

torch.eye(n=3)


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
# here the function returns an error becuase it accepts only integers not decimal numbers 

torch.eye(n=0.3)


TypeError: ignored

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra


'https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra'

## Function 3: torch.full

torch.full returns a tensor of size size with the values filled with fill_value
The size can be a list or a tuple.

In [ ]:
# Example 1 - working

# The size here is a tuple


torch.full(size=(3,2), fill_value=10)


tensor([[10, 10],
        [10, 10],
        [10, 10]])

Explanation about example

In [ ]:
# Example 2 - working

# The size here is a tuple

torch.full(size=[2, 3, 4], fill_value=5)

tensor([[[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]],

        [[5, 5, 5, 5],
         [5, 5, 5, 5],
         [5, 5, 5, 5]]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
# this input to the size of length less than 2 will not be accepted, 
# the input of the  size must be an array or tuple of length 2 or more 
 
torch.full(size= (1), fill_value=5)



TypeError: ignored

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra


'https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra'

## Function 4: torch.cat

torch.cat concatenates a sequence of tensors over the specified dimension dim. 

All the tensors must be of the same shape

In [ ]:
# Example 1 - working

a = torch.ones(3,2)
b = torch.zeros(3,2)
torch.cat((a, b)) # default dim=0


tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

Explanation about example

In [ ]:
# Example 2 - working

x = torch.full((3,3), fill_value=4)
y = torch.full((3,3), fill_value=7)
torch.cat((x, y), dim=1)

tensor([[4, 4, 4, 7, 7, 7],
        [4, 4, 4, 7, 7, 7],
        [4, 4, 4, 7, 7, 7]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

# the dimension has to be an integer or it reurns an error 

x = torch.full((3,3), fill_value=4)
y = torch.full((3,3), fill_value=7)
torch.cat((x, y), dim=1.5)


TypeError: ignored

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5: torch.take

torch.take returns a tensor with the elements of the input tensors at the given indices. 

The input tensor is treated as a 1D tensor to return the values.

In [ ]:
# Example 1 - working (change this)

# 1D input Tensor
b = torch.tensor([10, 20, 30, 40, 50])
torch.take(b, torch.tensor([2]))

tensor([30])

Explanation about example

In [ ]:
# Example 2 - working

# 2D input tensor
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.take(a, torch.tensor([3,4]))


tensor([4, 5])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

# in this function the index specified is more than what the tensor provides 

# 2D input tensor
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.take(a, torch.tensor([6]))


RuntimeError: ignored

Explanation about example

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra


'https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra'

## Conclusion

Some basic functions in Pytorch has been covered the next thing we will be looking at will be logistic  regression 

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra


'https://jovian.ai/rj-0605/how-to-use-pytorch-tensors-for-linear-algebra'